export const KINTOBLOCK_CREATE_SUCCESS = 'KINTOBLOCK_CREATE_SUCCESS'
export const SIGNUP_WELCOME = 'SIGNUP_WELCOME'
export const WORKSPACE_FIRST_SUCCESS = 'WORKSPACE_FIRST_SUCCESS'
export const DEPLOY_FIRST_SUCCESS = 'DEPLOY_FIRST_SUCCESS'
