export const REFRESH_PAGE = 'REFRESH_PAGE'
export const NOT_FOUND = 'NOT_FOUND'
export const INVALID_WORKSPACE_INVITE = 'INVALID_WORKSPACE_INVITE'
export const ERROR_WITH_MESSAGE_AND_CONTINUE_OPTION =
  'ERROR_WITH_MESSAGE_AND_CONTINUE_OPTION'
